# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-19 14:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aspath', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('showtoggle', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date', models.DateTimeField()),
                ('seen', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('picture', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olsp.Categories')),
            ],
        ),
        migrations.CreateModel(
            name='CourseChat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date', models.DateTimeField()),
                ('seen', models.CharField(max_length=10)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olsp.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('matpath', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olsp.Chapter')),
            ],
        ),
        migrations.CreateModel(
            name='Superuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=255)),
                ('phonenumber', models.IntegerField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Taken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField()),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olsp.Chapter')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olsp.Course')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olsp.Material')),
            ],
        ),
        migrations.CreateModel(
            name='TakenCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olsp.Course')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('origin', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('profession', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('registerdate', models.DateField(default=datetime.date(2018, 5, 19))),
                ('password', models.CharField(max_length=255)),
                ('phonenumber', models.IntegerField(max_length=16)),
                ('status', models.CharField(max_length=10)),
                ('picture', models.CharField(max_length=100)),
                ('lastact', models.DateField(default=datetime.date(2018, 5, 19))),
            ],
        ),
        migrations.AddField(
            model_name='takencourse',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olsp.User'),
        ),
        migrations.AddField(
            model_name='taken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olsp.User'),
        ),
        migrations.AddField(
            model_name='coursechat',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olsp.User'),
        ),
        migrations.AddField(
            model_name='course',
            name='inst',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olsp.User'),
        ),
        migrations.AddField(
            model_name='chat',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reciver', to='olsp.User'),
        ),
        migrations.AddField(
            model_name='chat',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='olsp.User'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olsp.Course'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olsp.Material'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olsp.User'),
        ),
    ]
